spring.application.name=demo
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
security.jwt.secret=mi-clave-secreta-local-de-prueba-con-mas-de-32-caracteres
security.jwt.expiration-minutes=60